/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import {
  useGLTF,
} from "@react-three/drei";

export default function Island() {
  const { scene } = useGLTF("/3d/island.glb");

  return (
    <>
      <mesh
        position={[0, -0.5, 0]}
        scale={[0.11, 0.11, 0.11]}
        rotation={[0, -1.65, 0]}
      >
        <primitive object={scene} />
      </mesh>
    </>
  );
}
