/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { a } from '@react-spring/three'

export default function Name(props) {
  const { nodes, materials } = useGLTF("/3d/name.glb");
  return (
    <a.group {...props} >
      <mesh
        geometry={nodes.imagetostl_mesh0.geometry}
        material={materials.mat0}
      />
      <mesh
        geometry={nodes.imagetostl_mesh1.geometry}
        material={materials.mat1}
      />
      <mesh
        geometry={nodes.imagetostl_mesh2.geometry}
        material={materials.mat2}
      />
      <mesh
        geometry={nodes.imagetostl_mesh3.geometry}
        material={materials.mat3}
      />
      <mesh
        geometry={nodes.imagetostl_mesh4.geometry}
        material={materials.mat4}
      />
      <mesh
        geometry={nodes.imagetostl_mesh5.geometry}
        material={materials.mat5}
      />
      <mesh
        geometry={nodes.imagetostl_mesh6.geometry}
        material={materials.mat6}
      />
      <mesh
        geometry={nodes.imagetostl_mesh7.geometry}
        material={materials.mat7}
      />
      <mesh
        geometry={nodes.imagetostl_mesh8.geometry}
        material={materials.mat8}
      />
      <mesh
        geometry={nodes.imagetostl_mesh9.geometry}
        material={materials.mat9}
      />
      <mesh
        geometry={nodes.imagetostl_mesh10.geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes.imagetostl_mesh11.geometry}
        material={materials.mat11}
      />
      <mesh
        geometry={nodes.imagetostl_mesh12.geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes.imagetostl_mesh13.geometry}
        material={materials.mat13}
      />
      <mesh
        geometry={nodes.imagetostl_mesh14.geometry}
        material={materials.mat14}
      />
      <mesh
        geometry={nodes.imagetostl_mesh15.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.imagetostl_mesh16.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.imagetostl_mesh17.geometry}
        material={materials.mat17}
      />
    </a.group>
  );
}
