/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { Text3D } from "@react-three/drei";
import fontJson from "./font.json";

export default function Name(props) {
  return (
    <Text3D
      font={fontJson}
      scale={[0.5, 0.5, 0.5]}
      position={[-1.4, -0.8, 2.9]}
    >
      WinnieS
      <meshNormalMaterial />
    </Text3D>
  );
}
